# Generated by Django 4.2 on 2023-04-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='Sudharsan_Annamalai', max_length=50),
        ),
    ]
